- name: create apollo_adminservice directory
  file:
    path: '{{ apollo_home }}/{{ apollo_adminservice }}'
    state: directory

- name: unzip '{{ apollo_adminservice_package }}'
  unarchive:
    src: '{{ apollo_adminservice_url }}'
    dest: '{{ apollo_home }}/{{ apollo_adminservice }}'
    remote_src: yes
    keep_newer: yes
  tags: unzip 

- name: copy mysql configuration template
  template:
    src: 'application-meta-{{ env }}.j2'
    dest: '{{ apollo_home }}/{{ apollo_adminservice }}/config/application-github.properties'

# - name: copy systemd file
#   template:
#     src: 'application-adminservice-systemd.j2'
#     dest: '/etc/systemd/system/{{ apollo_adminservice }}.service'
#   notify: restart adminservice

# - name: systemd '{{ apollo_adminservice }}'
#   systemd:
#     name: apollo-adminservice
#     daemon_reload: yes
#     enabled: yes

- name: Start Apollo AdminServer
  shell: '/bin/bash "{{ apollo_home }}/{{ apollo_adminservice }}/scripts/startup.sh" '
  environment: 
    JAVA_HOME: "{{ java_home }}"