- name: create apollo_configservice directory
  file:
    path: '{{ apollo_home }}/{{ apollo_configservice }}'
    state: directory

- name: unzip '{{ apollo_configservice_package }}'
  unarchive:
    src: '{{ apollo_configservice_url }}'
    dest: '{{ apollo_home }}/{{ apollo_configservice }}'
    remote_src: yes
    keep_newer: yes
  tags: unzip 

- name: copy mysql configuration template
  template:
    src: 'application-meta-{{ env }}.j2'
    dest: '{{ apollo_home }}/{{ apollo_configservice }}/config/application-github.properties'

# - name: copy systemd file
#   template:
#     src: 'application-configservice-systemd.j2'
#     dest: '/etc/systemd/system/{{ apollo_configservice }}.service'
#   notify: restart configservice

# - name: systemd '{{ apollo_configservice }}'
#   systemd:
#     name: apollo-configservice
#     daemon_reload: yes
#     enabled: yes

- name: Start Apollo ConfigServer
  shell: '/bin/bash "{{ apollo_home }}/{{ apollo_configservice }}/scripts/startup.sh" '
  environment: 
    JAVA_HOME: "{{ java_home }}"