FROM gradle:6.5-jdk8

ENV ANDROID_SDK_FILENAME "commandlinetools-linux-6858069_latest.zip"
ENV ANDROID_SDK_URL "https://dl.google.com/android/repository/${ANDROID_SDK_FILENAME}"
ENV ANDROID_HOME "/opt/android-sdk-linux"
ENV PATH "${PATH}:${ANDROID_HOME}/cmdline-tools/latest/bin"
ENV PATH "${PATH}:${ANDROID_HOME}/platform-tools"
ENV PATH "${PATH}:${ANDROID_HOME}/build-tools/29.0.2"
ENV PATH "${PATH}:${ANDROID_HOME}/build-tools/28.0.3"
ENV PATH "${PATH}:${ANDROID_HOME}/emulator"

ENV FLUTTER_SDK_FILE "flutter_linux_2.0.4-stable.tar.xz"
ENV FLUTTER_SDK_URL "https://storage.googleapis.com/flutter_infra/releases/stable/linux/${FLUTTER_SDK_FILE}"
ENV FLUTTER_HOME "/opt/flutter"
ENV PATH "${PATH}:${FLUTTER_HOME}/bin"

# Installs i386 architecture required for running 32 bit Android tools
RUN dpkg --add-architecture i386 && \
    apt-get update -y && \
    apt-get install -y libc6:i386 libgcc1:i386 libncurses5:i386 libstdc++6:i386 zlib1g:i386 && \
    apt-get clean

# Installs Android SDK
RUN mkdir -p ${ANDROID_HOME}/cmdline-tools && \
    cd ${ANDROID_HOME}/cmdline-tools && \
    wget -q ${ANDROID_SDK_URL} && \
    unzip ${ANDROID_SDK_FILENAME} && \
    mv cmdline-tools latest && \
    rm ${ANDROID_SDK_FILENAME} && \
    echo y |sdkmanager "platform-tools" "platforms;android-29" "platforms;android-28" "build-tools;29.0.2" "build-tools;28.0.3"

# Installs Flutter SDK
RUN cd /opt && \
    git clone https://github.com/flutter/flutter.git -b stable --depth 1 && \
    flutter precache && \
    flutter doctor