- name: create canal dir
  file:
    path: "{{ server_base_path }}/canal"
    state: directory
    mode: 0755

- name: unarchive canal.tar.gz
  unarchive:
    remote_src: true
    src: "{{ server_base_path }}/canal.deployer-1.1.5.tar.gz"
    dest: "{{ server_base_path }}/canal"
    mode: 0755