{{- if or .Values.php.fpmEnabled .Values.php.ini }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-php-conf
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  additional.ini: |-
  {{- if .Values.php.ini }}
{{ .Values.php.ini  | indent 4 }}
  {{- end }}
  {{- if .Values.php.fpmEnabled }}
  zz-docker.conf: |-
    [global]
    daemonize = no
    [www]
    listen = /var/run/php/php-fpm.sock
    listen.mode = 0666
  {{- if .Values.php.fpm }}
{{ .Values.php.fpm  | indent 4 }}
  {{- end }}
  {{- end }}
{{- end }}