- name : download openresty packges
  get_url:
    url: "https://openresty.org/package/{{ ansible_facts['distribution']| lower }}/openresty.repo"
    dest: /etc/yum.repos.d
    mode: 0644
    force: yes

- name: create openresty dir
  file:
    path: "{{ data_path }}"
    state: directory
 

- name : download openresty packges
  get_url:
    url: "https://{{ oss_url }}/front/openresty_conf.tar.gz"
    dest: "{{ data_path }}"
    mode: 0644
    force: yes

- name : download openresty packges
  get_url:
    url: "https://{{ oss_url }}/front/www-ssr.tar.gz"
    dest: "{{ data_path }}"
    mode: 0644
    force: yes

- name : download openresty packges
  get_url:
    url: "https://{{ oss_url }}/front/poc-data-gateway-lua.tar.gz"
    dest: "{{ data_path }}"
    mode: 0644
    force: yes