- name: Download binary distribution package
  get_url:
    url: https://{{ oss_url }}/exporter/mysqld_exporter-0.13.0.linux-amd64.tar.gz
    dest: /tmp/mysqld_exporter-0.13.0.linux-amd64.tar.gz

- name: Unpack mysqld_exporter binary
  unarchive:
    src: "/tmp/mysqld_exporter-0.13.0.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Ensure _mysqld_exporter_binary_install_dir exists.
  become: true
  file:
    path: "{{ _mysqld_exporter_binary_install_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Propagate mysqld_exporter binaries
  become: true
  copy:
    src: "/tmp/mysqld_exporter-0.13.0.linux-amd64/mysqld_exporter"
    dest: "{{ _mysqld_exporter_binary_install_dir }}/mysqld_exporter"
    mode: 0755
    owner: root
    group: root
    remote_src: yes

- name: Copy the mysqld_exporter systemd service file
  become: true
  template:
    src: mysqld_exporter.service.j2
    dest: /etc/systemd/system/mysqld_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart mysqld_exporter

- name: Ensure mysqld exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: mysqld_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode