CREATE USER `dadi01`@`172.19.%.%` IDENTIFIED BY 'PFF2MawgfD6D';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE VIEW, SHOW VIEW ON *.* TO 'dadi01'@'172.19.%.%' IDENTIFIED BY 'PFF2MawgfD6D';
GRANT SELECT ON *.* TO 'dadi_read'@'%' IDENTIFIED BY 'BdvC4uajd'; 