CREATE USER `dadi01`@`172.19.%.%` IDENTIFIED BY 'xxxxxxx';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE VIEW, SHOW VIEW ON *.* TO 'dadi01'@'172.19.%.%' IDENTIFIED BY 'xxxxxxxx';
GRANT SELECT ON *.* TO 'dadi_read'@'%' IDENTIFIED BY 'xxxxxx'; 

 DROP USER 'dadi01'@'172.19.%.%';