- name: create jenkins dir
  file:
    path: "{{ data_path }}"
    state: directory
    mode: 0755

- name: unarchive tools.tar.gz
  unarchive:
    remote_src: true
    src: "{{ server_base_path }}/tools.tar.gz"
    dest: "{{ server_base_path }}/"
    mode: 0755

- name: add link
  file:
    src: "{{ server_base_path }}/apache-tomcat-{{ tomcat_version }}"
    dest: "{{ server_base_path }}/tomcat"
    state: link